### ISSUE TITLE
sandbox issues starting the app in linux (Debian Buster)

### ISSUE THREAD

**Issue by oli-ver** [iiFir3z/Apple-Music-Electron#2]
Hey @iiFir3z,

great idea to develop this app! Thanks for all the effort.

Starting the application in linux is right now only possible with the `--no-sandbox` parameter. I read in https://github.com/electron/electron/issues/18265 that this is somehow related to operating system configuration or chrome_sandbox permissions.

I also noticed that the apps still opens beta.music.apple.com, but isn't the web app out of beta and music.apple.com can be used?

Playing songs does not work right now, the error message is something like "This browser is not supported. Try using Safari to access music.apple.com".

Here are the console logs:

```
$ ./apple-music-electron --no-sandbox
(node:5788) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:5788) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (/opt/Apple Music/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:5788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5788) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5788) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at WebFrame.e.startsWith.e.startsWith.WebFrame.<computed> [as _executeJavaScript] (electron/js2c/renderer_init.js:87:1576)
    at electron/js2c/renderer_init.js:115:453
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:99:375)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:925)
(node:5788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:5788) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at WebFrame.e.startsWith.e.startsWith.WebFrame.<computed> [as _executeJavaScript] (electron/js2c/renderer_init.js:87:1576)
    at electron/js2c/renderer_init.js:115:453
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:99:375)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:925)
(node:5788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:5788) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at WebFrame.e.startsWith.e.startsWith.WebFrame.<computed> [as _executeJavaScript] (electron/js2c/renderer_init.js:87:1576)
    at electron/js2c/renderer_init.js:115:453
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:99:375)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:925)
(node:5788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:5788) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at WebFrame.e.startsWith.e.startsWith.WebFrame.<computed> [as _executeJavaScript] (electron/js2c/renderer_init.js:87:1576)
    at electron/js2c/renderer_init.js:115:453
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:99:375)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:925)
(node:5788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
```
I tested it on Debian Buster.

**Comment by iiFir3z** [comment]
Intresting bug. Ill check it out, mind telling me what type of package you installed it with (.deb, .appimage, .snap)?

**Comment by oli-ver** [comment]
Great, thanks. I used the .deb installer.

**Comment by iiFir3z** [comment]
Just added the manual prefix to the app ill push new builds shortly.

https://github.com/iiFir3z/Apple-Music-Electron/commit/cd5ece383f2275ab50fca89a3d3a09b6e5d601c4
